import typography from '@tailwindcss/typography'

export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,ts,tsx,js,jsx}"
  ],
  theme: {
    extend: {
      colors: {
        // Brand roles: values come from the active theme (src/theme/)
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        primaryDark: "rgb(var(--color-primary-dark) / <alpha-value>)",
        primaryLight: "rgb(var(--color-primary-light) / <alpha-value>)",
        primaryDeep: "rgb(var(--color-primary-deep) / <alpha-value>)",
        primaryDarkest: "rgb(var(--color-primary-darkest) / <alpha-value>)",
        primarySoft: "rgb(var(--color-primary-soft) / <alpha-value>)",
        primaryFaint: "rgb(var(--color-primary-faint) / <alpha-value>)",
        primaryAction: "rgb(var(--color-primary-action) / <alpha-value>)",
        primaryActionHover: "rgb(var(--color-primary-action-hover) / <alpha-value>)",
        brandAccent: "rgb(var(--color-brand-accent) / <alpha-value>)",
        brandIndicator: "rgb(var(--color-brand-indicator) / <alpha-value>)",
        brandAccentSoft: "rgb(var(--color-brand-accent-soft) / <alpha-value>)",
        bgSoft: "rgb(var(--color-bg-soft) / <alpha-value>)",
        surfaceTint: "rgb(var(--color-surface-tint) / <alpha-value>)",
        surfacePage: "rgb(var(--color-surface-page) / <alpha-value>)",
        surfaceDark: "rgb(var(--color-surface-dark) / <alpha-value>)",

        // Theme-independent
        destructive: "rgb(var(--color-destructive) / <alpha-value>)",
        destructiveSoft: "rgb(var(--color-destructive-soft) / <alpha-value>)",
        surfaceMuted: "rgb(var(--color-surface-muted) / <alpha-value>)",
        borderSubtle: "rgb(var(--color-border-subtle) / <alpha-value>)",
        onDark: "rgb(var(--color-on-dark) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        successTint: "rgb(var(--color-success-tint) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        dangerTint: "rgb(var(--color-danger-tint) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        warningTint: "rgb(var(--color-warning-tint) / <alpha-value>)",
        info: "rgb(var(--color-info) / <alpha-value>)",
        infoTint: "rgb(var(--color-info-tint) / <alpha-value>)",
        statusGreen: "rgb(var(--color-status-green) / <alpha-value>)",
        statusYellow: "rgb(var(--color-status-yellow) / <alpha-value>)",
        statusOrange: "rgb(var(--color-status-orange) / <alpha-value>)",
        statusSlate: "rgb(var(--color-status-slate) / <alpha-value>)",
        textStrong: "rgb(var(--color-text-strong) / <alpha-value>)",
        textHeading: "rgb(var(--color-text-heading) / <alpha-value>)",
        textMuted: "rgb(var(--color-text-muted) / <alpha-value>)",
        textFaint: "rgb(var(--color-text-faint) / <alpha-value>)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        '2xl': "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        7: "var(--space-7)",
        8: "var(--space-8)",
        9: "var(--space-9)",
        10: "var(--space-10)",
        11: "var(--space-11)",
        12: "var(--space-12)",
      },
      fontFamily: {
        sans: ["var(--font-family-sans)"],
      },
      fontSize: {
        'display-1': ["var(--text-display-1-size)", { lineHeight: "var(--text-display-1-line-height)", fontWeight: "var(--font-weight-bold)" }],
        'headline-1': ["var(--text-headline-1-size)", { lineHeight: "var(--text-headline-1-line-height)", fontWeight: "var(--font-weight-bold)" }],
        'headline-2': ["var(--text-headline-2-size)", { lineHeight: "var(--text-headline-2-line-height)", fontWeight: "var(--font-weight-semibold)" }],
        'headline-3': ["var(--text-headline-3-size)", { lineHeight: "var(--text-headline-3-line-height)", fontWeight: "var(--font-weight-semibold)" }],
        lead: ["var(--text-lead-size)", { lineHeight: "var(--text-lead-line-height)", fontWeight: "var(--font-weight-regular)" }],
        body: ["var(--text-body-size)", { lineHeight: "var(--text-body-line-height)", fontWeight: "var(--font-weight-regular)" }],
        caption: ["var(--text-caption-size)", { lineHeight: "var(--text-caption-line-height)", fontWeight: "var(--font-weight-regular)" }],
      },
    },
  },
  plugins: [typography],
}
